### ISSUE TITLE
Poker Hand Rankings #10

### ISSUE THREAD

**Issue by verkruemelt** [Phreshhh/PokerClock#2]
This is not a high card, it's a straight:
![{CECBDB29-99AE-413F-821D-C632F0BA5414} png](https://user-images.githubusercontent.com/1926264/59584936-9b5a3d80-90df-11e9-929e-46ad51940494.jpg)

**Comment by Phreshhh** [comment]
Hi!

Really.. Thanks.
If I make upgrade or changes in the app, i 'll change this picture too, but as i see, i maked this only myself.. :)
